export default {
    world: "334b2cac-34a6-4da7-ae39-a9450be68d33",
    width: 2,
    height: 2,
    rooms: {
        r1c1: {
            title: "",
            description: "",
            n: 0,
            s: 0,
            e: 0,
            w: 3275,
            tile_num: 1,
            col: 1,
            row: 1,
        },
        r1c0: {
            title: "",
            description: "",
            n: 3276,
            s: 0,
            e: 3274,
            w: 0,
            tile_num: 7,
            col: 0,
            row: 1,
        },
        r0c0: {
            title: "",
            description: "",
            n: 0,
            s: 3275,
            e: 3277,
            w: 0,
            tile_num: 8,
            col: 0,
            row: 0,
        },
        r0c1: {
            title: "",
            description: "",
            n: 0,
            s: 0,
            e: 0,
            w: 3276,
            tile_num: 1,
            col: 1,
            row: 0,
        },
    },
    room_count: 4,
}
