export default {
    world: "3e101f7f-6302-4d4e-9be7-b82a2253e20e",
    width: 3,
    height: 3,
    rooms: {
        r1c1: {
            title: "",
            description: "",
            n: 0,
            s: 3279,
            e: 0,
            w: 0,
            tile_num: 4,
            col: 1,
            row: 1,
        },
        r2c1: {
            title: "",
            description: "",
            n: 3278,
            s: 0,
            e: 0,
            w: 3280,
            tile_num: 10,
            col: 1,
            row: 2,
        },
        r2c0: {
            title: "",
            description: "",
            n: 3281,
            s: 0,
            e: 3279,
            w: 0,
            tile_num: 7,
            col: 0,
            row: 2,
        },
        r1c0: {
            title: "",
            description: "",
            n: 3282,
            s: 3280,
            e: 0,
            w: 0,
            tile_num: 6,
            col: 0,
            row: 1,
        },
        r0c0: {
            title: "",
            description: "",
            n: 0,
            s: 3281,
            e: 3283,
            w: 0,
            tile_num: 8,
            col: 0,
            row: 0,
        },
        r0c1: {
            title: "",
            description: "",
            n: 0,
            s: 0,
            e: 3284,
            w: 3282,
            tile_num: 5,
            col: 1,
            row: 0,
        },
        r0c2: {
            title: "",
            description: "",
            n: 0,
            s: 3285,
            e: 0,
            w: 3283,
            tile_num: 9,
            col: 2,
            row: 0,
        },
        r1c2: {
            title: "",
            description: "",
            n: 3284,
            s: 3286,
            e: 0,
            w: 0,
            tile_num: 6,
            col: 2,
            row: 1,
        },
        r2c2: {
            title: "",
            description: "",
            n: 3285,
            s: 0,
            e: 0,
            w: 0,
            tile_num: 2,
            col: 2,
            row: 2,
        },
    },
    room_count: 9,
}
